// The text of every file sync.mjs writes under src/generated/ except meta.ts,
// as a pure function of the ABI JSON. sync.mjs writes with it; generated.test.ts
// renders the same files from spec/abi and compares them byte for byte, which is
// what lets .gitattributes mark them linguist-generated: CI re-derives them.
//
// CommonJS so that both the ESM sync script and the jest suite can load it.
'use strict';
const { keccak_256 } = require('@noble/hashes/sha3');

const hex = (bytes) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
const canonicalType = (input) =>
  input.type === 'tuple' || input.type.startsWith('tuple')
    ? `(${input.components.map(canonicalType).join(',')})${input.type.slice('tuple'.length)}`
    : input.type;
const signature = (entry) => `${entry.name}(${(entry.inputs ?? []).map(canonicalType).join(',')})`;
const selectorOf = (entry) => `0x${hex(keccak_256(new TextEncoder().encode(signature(entry))).slice(0, 4))}`;
// `CancoreRouter` → `CANCORE_ROUTER`. An acronym of two or more capitals followed
// by a word gets its own underscore (`CNRXStaking` → `CNRX_STAKING`); a single
// leading capital does not (`IBurnMintERC20` → `IBURN_MINT_ERC20`, as published).
const constName = (name) =>
  name.replace(/([A-Z]{2,})([A-Z][a-z])/g, '$1_$2').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();

/** src/generated/<Name>.ts; `source` is the path inside evm-contracts it was read from. */
const renderAbiModule = (name, abi, source) =>
  `// Generated by scripts/sync.mjs from evm-contracts/${source} — do not edit.\n` +
  `export const ${constName(name)}_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`;

/** src/generated/index.ts over the sorted snapshot names. */
const renderIndex = (names) => `${names.map((name) => `export { ${constName(name)}_ABI } from './${name}';`).join('\n')}\n`;

/** src/generated/errors.ts over [name, abi] pairs in snapshot order. */
const renderErrors = (entries) => {
  const blocks = [];
  for (const [name, abi] of entries) {
    const errors = abi.filter((e) => e.type === 'error');
    if (errors.length === 0) continue;
    const rows = errors.map((e) => `  '${selectorOf(e)}': '${signature(e)}',`).join('\n');
    blocks.push(
      `/** Custom errors of ${name}: 4-byte selector → signature, for readable reverts. */\n` +
        `export const ${constName(name)}_ERRORS: Readonly<Record<string, string>> = {\n${rows}\n};\n`,
    );
  }
  return `// Generated by scripts/sync.mjs — keccak256 of each custom error's signature, first 4 bytes.\n\n${blocks.join('\n')}`;
};

module.exports = { constName, renderAbiModule, renderIndex, renderErrors };
