#!/usr/bin/env node
// Pull the canonical ABI snapshots out of a checkout of Cancore-io/evm-contracts
// and write this package's data from them: the JSON snapshot under spec/, the
// `as const` TypeScript under src/generated/, the custom-error selector tables,
// and the release identity (version + bytecode hashes).
//
// The contracts repository is the source of truth; this package is a mirror an
// integrator can install. Nothing here is edited by hand — re-run the sync.
//
//   EVM_CONTRACTS_DIR=../evm-contracts npm run sync
import { keccak_256 } from '@noble/hashes/sha3';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const src = resolve(process.env.EVM_CONTRACTS_DIR ?? resolve(pkg, '../../../evm-contracts'));

const abiDir = join(src, 'abi');
const names = readdirSync(abiDir)
  .filter((f) => f.endsWith('.json') && f !== 'bytecode-hashes.json')
  .map((f) => f.replace(/\.json$/, ''))
  .sort();
if (names.length === 0) throw new Error(`no ABI snapshots under ${abiDir}`);

const version = JSON.parse(readFileSync(join(src, 'version.json'), 'utf8'));
const bytecode = JSON.parse(readFileSync(join(abiDir, 'bytecode-hashes.json'), 'utf8'));

mkdirSync(join(pkg, 'spec', 'abi'), { recursive: true });
mkdirSync(join(pkg, 'src', 'generated'), { recursive: true });

const hex = (bytes) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
const canonicalType = (input) =>
  input.type === 'tuple' || input.type.startsWith('tuple')
    ? `(${input.components.map(canonicalType).join(',')})${input.type.slice('tuple'.length)}`
    : input.type;
const signature = (entry) => `${entry.name}(${(entry.inputs ?? []).map(canonicalType).join(',')})`;
const selectorOf = (entry) => `0x${hex(keccak_256(new TextEncoder().encode(signature(entry))).slice(0, 4))}`;

const constName = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();

const indexLines = [];
const errorBlocks = [];
for (const name of names) {
  const abi = JSON.parse(readFileSync(join(abiDir, `${name}.json`), 'utf8'));
  writeFileSync(join(pkg, 'spec', 'abi', `${name}.json`), `${JSON.stringify(abi, null, 2)}\n`);
  const id = `${constName(name)}_ABI`;
  writeFileSync(
    join(pkg, 'src', 'generated', `${name}.ts`),
    `// Generated by scripts/sync.mjs from evm-contracts/abi/${name}.json — do not edit.\n` +
      `export const ${id} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  indexLines.push(`export { ${id} } from './${name}';`);

  const errors = abi.filter((e) => e.type === 'error');
  if (errors.length > 0) {
    const rows = errors.map((e) => `  '${selectorOf(e)}': '${signature(e)}',`).join('\n');
    errorBlocks.push(
      `/** Custom errors of ${name}: 4-byte selector → signature, for readable reverts. */\n` +
        `export const ${constName(name)}_ERRORS: Readonly<Record<string, string>> = {\n${rows}\n};\n`,
    );
  }
}

writeFileSync(
  join(pkg, 'src', 'generated', 'errors.ts'),
  `// Generated by scripts/sync.mjs — keccak256 of each custom error's signature, first 4 bytes.\n\n` +
    errorBlocks.join('\n'),
);
writeFileSync(
  join(pkg, 'src', 'generated', 'meta.ts'),
  `// Generated by scripts/sync.mjs from evm-contracts/version.json and abi/bytecode-hashes.json.\n\n` +
    `/** The evm-contracts release these ABIs were taken from. */\n` +
    `export const CONTRACTS_RELEASE = ${JSON.stringify({ version: version.version, releaseChannel: version.releaseChannel, updatedAt: version.updatedAt }, null, 2)} as const;\n\n` +
    `/**\n * keccak256 of the compiled creation and runtime bytecode per contract — what a\n * deployment can be checked against, independent of any address list.\n */\n` +
    `export const BYTECODE_HASHES = ${JSON.stringify(bytecode, null, 2)} as const;\n`,
);
writeFileSync(join(pkg, 'src', 'generated', 'index.ts'), `${indexLines.join('\n')}\n`);
console.log(`synced ${names.length} ABIs from ${src} (evm-contracts ${version.version})`);
