#!/usr/bin/env node
// Pull the canonical ABI snapshots out of a checkout of Cancore-io/evm-contracts
// and write this package's data from them: the JSON snapshot under spec/, the
// `as const` TypeScript under src/generated/, the custom-error selector tables,
// and the release identity (version + bytecode hashes).
//
// The contracts repository is the source of truth; this package is a mirror an
// integrator can install. Nothing here is edited by hand — re-run the sync.
//
//   EVM_CONTRACTS_DIR=../evm-contracts npm run sync
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import render from './render.cjs';

const { renderAbiModule, renderErrors, renderIndex } = render;

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, '..');
const src = resolve(process.env.EVM_CONTRACTS_DIR ?? resolve(pkg, '../../../evm-contracts'));

const abiDir = join(src, 'abi');
const names = readdirSync(abiDir)
  .filter((f) => f.endsWith('.json') && f !== 'bytecode-hashes.json')
  .map((f) => f.replace(/\.json$/, ''))
  .sort();
if (names.length === 0) throw new Error(`no ABI snapshots under ${abiDir}`);

const version = JSON.parse(readFileSync(join(src, 'version.json'), 'utf8'));
const bytecode = JSON.parse(readFileSync(join(abiDir, 'bytecode-hashes.json'), 'utf8'));

mkdirSync(join(pkg, 'spec', 'abi'), { recursive: true });
mkdirSync(join(pkg, 'src', 'generated'), { recursive: true });

const abis = names.map((name) => [name, JSON.parse(readFileSync(join(abiDir, `${name}.json`), 'utf8'))]);
for (const [name, abi] of abis) {
  writeFileSync(join(pkg, 'spec', 'abi', `${name}.json`), `${JSON.stringify(abi, null, 2)}\n`);
  writeFileSync(join(pkg, 'src', 'generated', `${name}.ts`), renderAbiModule(name, abi, `abi/${name}.json`));
}
writeFileSync(join(pkg, 'src', 'generated', 'errors.ts'), renderErrors(abis));
writeFileSync(
  join(pkg, 'src', 'generated', 'meta.ts'),
  `// Generated by scripts/sync.mjs from evm-contracts/version.json and abi/bytecode-hashes.json.\n\n` +
    `/** The evm-contracts release these ABIs were taken from. */\n` +
    `export const CONTRACTS_RELEASE = ${JSON.stringify({ version: version.version, releaseChannel: version.releaseChannel, updatedAt: version.updatedAt }, null, 2)} as const;\n\n` +
    `/**\n * keccak256 of the compiled creation and runtime bytecode per contract — what a\n * deployment can be checked against, independent of any address list.\n */\n` +
    `export const BYTECODE_HASHES = ${JSON.stringify(bytecode, null, 2)} as const;\n`,
);
writeFileSync(join(pkg, 'src', 'generated', 'index.ts'), renderIndex(names));
console.log(`synced ${names.length} ABIs from ${src} (evm-contracts ${version.version})`);
