// Pull the deployed gateway's OpenAPI document into spec/openapi.json, and write
// src/sdk-error-codes.ts from its SdkErrorCode enum.
//
// Usage: node scripts/refresh-spec.mjs [url-or-file]   (default: the api-dev document)
//
// Written with sorted keys and one field per line, so a refresh that changes
// nothing in the API changes nothing on disk, and one that does reads as a
// reviewable diff instead of a single 350 KB line. Arrays keep their order:
// `required`, `enum` and `parameters` come out of the backend code in a fixed
// order, and sorting them would rewrite the document rather than normalize it.
import { readFileSync, writeFileSync } from 'node:fs';

const url = process.argv[2] ?? 'https://api-dev.cancore.app/api-json';
const out = new URL('../spec/openapi.json', import.meta.url);
const codesOut = new URL('../src/sdk-error-codes.ts', import.meta.url);

let doc;
if (/^https?:\/\//.test(url)) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  doc = await res.json();
} else {
  doc = JSON.parse(readFileSync(url, 'utf8'));
}
// An error page or a half-booted stand must fail the refresh, not replace the snapshot.
if (typeof doc?.openapi !== 'string' || Object.keys(doc.paths ?? {}).length === 0) {
  throw new Error(`${url} did not return an OpenAPI document with paths`);
}
// A gateway that does not publish the registry yet must fail the refresh too: the client's union is this enum.
const codes = doc.components?.schemas?.SdkErrorCode?.enum;
if (!Array.isArray(codes) || codes.length === 0 || !codes.every((c) => typeof c === 'string' && c !== '')) {
  throw new Error(`${url} has no components.schemas.SdkErrorCode enum of strings`);
}

const sortKeys = (v) =>
  Array.isArray(v) ? v.map(sortKeys)
  : v !== null && typeof v === 'object' ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sortKeys(v[k])]))
  : v;

writeFileSync(out, `${JSON.stringify(sortKeys(doc), null, 2)}\n`);
// Spec order, like the document: a reordered enum is a real diff, not noise to sort away.
writeFileSync(
  codesOut,
  `// Generated by scripts/refresh-spec.mjs from components.schemas.SdkErrorCode of spec/openapi.json. Do not edit.
export const SDK_ERROR_CODES = [
${codes.map((c) => `  '${c}',`).join('\n')}
] as const;

export type SdkErrorCode = (typeof SDK_ERROR_CODES)[number];
`,
);
console.log(Object.keys(doc.paths).length, 'paths,', codes.length, 'error codes');
