import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// .gitattributes marks src/generated/<Name>.ts, index.ts and errors.ts as
// linguist-generated: folded in diffs, out of the review size budget. That is
// only sound while CI re-derives them, so this suite renders each one from the
// reviewed spec/abi JSON with the code sync.mjs writes them with and compares
// the whole file, byte for byte. meta.ts and typedData.ts are not marked:
// neither is derivable from spec/ alone, so a reviewer reads them.

type AbiEntry = { type: string; name?: string; inputs?: unknown[] };
type Render = {
  renderAbiModule(name: string, abi: AbiEntry[], source: string): string;
  renderIndex(names: string[]): string;
  renderErrors(entries: Array<[string, AbiEntry[]]>): string;
};
const render = require('../scripts/render.cjs') as Render;

const generatedDir = join(__dirname, 'generated');
const specDir = join(__dirname, '..', 'spec', 'abi');
const names = readdirSync(specDir).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')).sort();
const abiOf = (name: string) => JSON.parse(readFileSync(join(specDir, `${name}.json`), 'utf8')) as AbiEntry[];
const generated = (file: string) => readFileSync(join(generatedDir, file), 'utf8');

test('src/generated holds exactly one module per snapshot plus the four shared files', () => {
  const files = readdirSync(generatedDir).sort();
  expect(files).toEqual([...names.map((n) => `${n}.ts`), 'errors.ts', 'index.ts', 'meta.ts', 'typedData.ts'].sort());
});

test.each(names)('%s.ts is exactly what sync.mjs renders from spec/abi/%s.json', (name) => {
  const text = generated(`${name}.ts`);
  // The header names where in evm-contracts the ABI was read; that path is the
  // one thing spec/ does not record, so it is pinned to the two legal shapes.
  const source = /^\/\/ Generated by scripts\/sync\.mjs from evm-contracts\/((?:abi|vendor)\/[A-Za-z0-9]+\.json) — do not edit\.\n/.exec(text)?.[1];
  expect([`abi/${name}.json`, `vendor/${name}.json`]).toContain(source);
  expect(text).toBe(render.renderAbiModule(name, abiOf(name), source ?? ''));
});

test('index.ts is exactly what sync.mjs renders', () => {
  expect(generated('index.ts')).toBe(render.renderIndex(names));
});

test('errors.ts is exactly what sync.mjs renders', () => {
  expect(generated('errors.ts')).toBe(render.renderErrors(names.map((n) => [n, abiOf(n)])));
});
